language: java

jdk:
  - oraclejdk8
  - openjdk7

notifications:
  email:
    recipients:
      - rglszl@gmail.com
      - reischl.barnabas@gmail.com
      
    on_success: never
    on_failure: always

